name: CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read # able to read the code
  packages: write # able to push Docker image to GHCR --> docker push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/csv-processor:latest .

      - name: Run tests
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/csv-processor:latest pytest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/csv-processor:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/csv-processor
            docker compose -f docker-compose.prod.yml pull app
            docker compose -f docker-compose.prod.yml up -d